export const PAGE_LIST_REQUEST = 'PAGE_LIST_REQUEST'
export const PAGE_LIST_SUCCESS = 'PAGE_LIST_SUCCESS'
export const PAGE_LIST_FAIL = 'PAGE_LIST_FAIL'

export const PAGE_DETAILS_REQUEST = 'PAGE_DETAILS_REQUEST'
export const PAGE_DETAILS_SUCCESS = 'PAGE_DETAILS_SUCCESS'
export const PAGE_DETAILS_FAIL = 'PAGE_DETAILS_FAIL'

export const PAGE_CREATE_REQUEST = 'PAGE_CREATE_REQUEST'
export const PAGE_CREATE_SUCCESS = 'PAGE_CREATE_SUCCESS'
export const PAGE_CREATE_FAIL = 'PAGE_CREATE_FAIL'

export const PAGE_DELETE_REQUEST = 'PAGE_DELETE_REQUEST'
export const PAGE_DELETE_SUCCESS = 'PAGE_DELETE_SUCCESS'
export const PAGE_DELETE_FAIL = 'PAGE_DELETE_FAIL'

export const PAGE_UPDATE_REQUEST = 'PAGE_UPDATE_REQUEST'
export const PAGE_UPDATE_SUCCESS = 'PAGE_UPDATE_SUCCESS'
export const PAGE_UPDATE_FAIL = 'PAGE_UPDATE_FAIL'

export const USER_EMAIL_REQUEST = 'USER_EMAIL_REQUEST'
export const USER_EMAIL_SUCCESS = 'USER_EMAIL_SUCCESS'
export const USER_EMAIL_FAIL = 'USER_EMAIL_FAIL'